### ISSUE TITLE
[Issue] Error adding entities for domain climate with platform climate_template

### ISSUE THREAD

**Issue by GregoryKowalik** [jcwillox/hass-template-climate#11]
Hi, 

I'm facing an issue with setting up my climate entity on HA 2022.7.4. The logs say it cannot be setup because of current temperature issue. Even if I setup it to a fixed value it still fails to load:

  **platform: climate_template
    name: Klimatyzacja w pracowni
    modes:
      - "off"
      - "dry"
      - "cool"
      - "fan_only"
    min_temp: 18
    max_temp: 32
    precision: 1.0
    #current_temperature_template: "{{ states('sensor.homematic_pracownia_temperature') }}"
    current_temperature_template: 22
    swing_mode_template: "{{ states('switch.swing') }}"**

This is what Logger throws:

Logger: homeassistant.components.climate
Source: custom_components/climate_template/climate.py:216
Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 14:56:20 (2 occurrences)
Last logged: 14:56:20

Error adding entities for domain climate with platform climate_template
Error while setting up climate_template platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/climate_template/climate.py", line 216, in async_added_to_hass
    self._current_temp = float(
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by GregoryKowalik** [comment]
Hi,
after HA upgrade to 2022.7.5 it automagically started to work. Apparently the update helped so I'm closing the issue.
Thanks
Greg
