### ISSUE TITLE
Component failure on recent HA 2022.4

### ISSUE THREAD

**Issue by GregoryKowalik** [jcwillox/hass-template-climate#5]
Hi,

it's me again with new issue caused by recent HA update ;) Climate template fails to load due to some changes on built-in fan component, I guess. Take a look at the log below. I hope this will be quick fix as for the previous issue :)

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/climate_template/climate.py", line 26, in <module>
    from homeassistant.components.fan import SPEED_HIGH, SPEED_LOW, SPEED_MEDIUM
ImportError: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
```

Thanks
Greg

**Comment by jcwillox** [comment]
Indeed it is a quick fix as it's already been fixed with version 0.2.0 👍, HACS should have picked up the new version by now.

This was also reported in #4
